name: Deploy to Bluehost via FTP
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.BLUEHOST_HOST }}
          username: ${{ secrets.BLUEHOST_USERNAME }}
          password: ${{ secrets.BLUEHOST_PASSWORD }}
          port: ${{ secrets.BLUEHOST_PORT }}
          local-dir: './'
          server-dir: '/public_html/cdad/'
